### PR TITLE
Example config for traefik v2.2

### PR DESCRIPTION
**Pull request by lbayerlein**
Added a working traefik example. Certificates will be created on every start.

### CODE REVIEW

**Comment by ansuz** [comment]
I created [this repository](https://github.com/xwiki-labs/cryptpad-docker) as a place to keep community-curated configuration files related to docker. It's not quite ready to go, which is the only reason this main repository still contains docker-related files. My aim is to only include configuration examples which the development team explicitly supports. Our policy for supported configurations is described [here](https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js#L2-L20).

I'd be happy to merge a PR to the above docker repo and to grant write access to it if the current members agree and if you're willing to provide continued support for this patch (ie. responding to related issues and PRs).

**Comment by lbayerlein** [comment]
Sure, I wanted to give some sort of example for a possible deployment.
I am happy to help, so if you wanted me to give support, I will do :)

**Comment by promasu** [comment]
Thanks a lot. I'll use it when finishing up the cryptpad-docker repository. I'll reach out to you if i have questions about it :D

**Comment by promasu** [comment]
Is integrated in the xwiki-labs/cryptpad-docker repository. Pull Request can be closed

**Pull request closed without merging**
