### PR TITLE
Fix docker build

### PR DESCRIPTION
**Pull request by kpcyrd**
This fixes the `Failed at the heapdump@0.3.9 install script 'node-gyp rebuild'.` issue so docker builds again.

### CODE REVIEW

**Comment by ansuz** [comment]
We don't use docker ourselves, so I have no issues merging this if it suits your use case.

I wonder, however, if you'll be able to use the heap dump functionality while the app is contained in docker. It's there for debugging purposes, and if it will not be used, a simpler solution would be for us to comment out the heapdump require call in `config.example.js`.

**Comment by kpcyrd** [comment]
Technically you could `docker exec` into the container if needed, but getting rid of heapdump would work as well as it's currently listed as a dev dependency. I've started using cryptpad with docker recently, please feel free to ping me on github if there are any  docker related issues you need reviewed. :)

**Comment by ansuz** [comment]
I'm going to comment out heapdump from the example config file.

Dev dependencies are skipped if you install with `npm install --production`, so if the docker configuration does that, I believe everything should work again.

**Comment by kpcyrd** [comment]
@ansuz thanks, I've updated my PR.

**Pull request merged**
