### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by heticor915**
Hi I would like to add spanish support to cryptpad, I've follow the standard rules for translatations. Add the hacktoberfest label to this repo, There're many in the world that want to contribute to this repo

### CODE REVIEW

**Comment by heticor915** [comment]
after Checking the robot it seems that the problem is not due to my translation perhaps to a missing semicolon in **www/slide/slide.js: line 213, col 26, Missing semicolon**.

**Comment by ansuz** [comment]
I'll see about resolving the errors on our side and pulling your changes in ASAP.

Thanks for your contributions!

**Comment by heticor915** [comment]
I will be happy when the PR be accepted :smile:

**Comment by ansuz** [comment]
Hi again @heticor915.

I've reviewed your PR, and there were a few issues with it.

1. It's based off of master, and not our development branch [soon](https://github.com/xwiki-labs/cryptpad/tree/soon).
  - that's hardly your fault, as there was no documentation about adding translations, we'll work on this
  - I've gone ahead and merged it into soon, however...
2. Since it's not based against our development branch, there are a few keys that are missing.
  - my knowledge of Spanish is limited, so I'll need some more help with this
  - to make things a little easier, and to make sure we're aware of translation issues in the future, I added [a test](https://github.com/xwiki-labs/cryptpad/commit/841ded8fdc403c53dda9cdffa0a58532f4a83993) that will let us know when a translation is missing a key which is present in the default English version.
  - the report on which keys are missing is included below

```
key [yourself] is missing from translation [es]
key [anonymousUsers] is missing from translation [es]
key [anonymousUser] is missing from translation [es]
key [share] is missing from translation [es]
key [users] is missing from translation [es]
key [editing] is missing from translation [es]
key [viewing] is missing from translation [es]
key [editShare] is missing from translation [es]
key [editShareTitle] is missing from translation [es]
key [viewShare] is missing from translation [es]
key [viewShareTitle] is missing from translation [es]
key [viewOpen] is missing from translation [es]
key [viewOpenTitle] is missing from translation [es]
key [header_xwiki] is missing from translation [es]
```

Once those have been added, I'll see about getting this deployed as soon as possible. Thanks for your contribution!

**Comment by ansuz** [comment]
I forgot to mention, the fixes I made are in a branch: [espanol](https://github.com/xwiki-labs/cryptpad/tree/espanol).

You'll need to pull that into your PR.

**Comment by heticor915** [comment]
Hi @ansuz  I'll review  this weekend, I'm in exams at my university. When it's done I will let you know.

**Comment by ansuz** [comment]
No rush, we'll tidy things up on our end. Good luck with your exams!

**Comment by heticor915** [comment]
Hi @ansuz I was checking the files that I commited,  I can not find the keys that are missing for the translation, I would like to pass by the irc channel to know the team and help me with this. Please What is the best time to get inside the irc channel ?

**Comment by ansuz** [comment]
I'm typically available online during my work hours, some time between 9:00 and 18:00 Paris time.

**Comment by ansuz** [comment]
Hi @heticor915,

Things are stable on our end now, but we had to add some new keys. I translated the keys myself, with some help from Google translate. They key changes are in [this commit](https://github.com/xwiki-labs/cryptpad/commit/f1bb63f915f929087115cd4f936d1a0d04b135b2).

Let me know if anything needs to be corrected. If not, we should be clear to merge and deploy.

Thanks again.

**Comment by heticor915** [comment]
@ansuz cool, I've added a few comments in line in your commit, I was thinking in [this ](https://www.google.com.co/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi86dCYlI7QAhWGLyYKHZQyAOkQFggeMAA&url=https%3A%2F%2Fbitcoin.org%2Fbitcoin.pdf&usg=AFQjCNE1QrMbFOhwJkCI2-Jj0eiZ_7YeyA&sig2=oNSnkg8fWa_05ZFtWsj9_Q)paper when did you mention nakamoto blockchain, Is this correct ? maybe we can add a reference using  a href.. html tag. Sorry for be too late I'm fighting with my Datastructure course treaps and rbt's seems advanced to digest in two weeks :smile: . I've reviewed your translation and is ok acording to debian rules, Just the comments present inconsistencies.

**Comment by ansuz** [comment]
Thanks for the review! I've updated a few keys in [this commit](https://github.com/xwiki-labs/cryptpad/commit/779b3914f9b47f87fe4461f92db88d906fb67995), which I'm going to merge right away.

If you notice any errors that slipped in, please let me know.

**Comment by ansuz** [comment]
Spanish translations have been merged into [soon](https://github.com/xwiki-labs/cryptpad/tree/soon) and will be in master and live on the site soon.

Thanks again for the help!

**Comment by heticor915** [comment]
Nice @ansuz I'm very happy to see this :rocket:  :+1:

**Comment by ansuz** [comment]
Me too!

**Comment by ansuz** [comment]
https://twitter.com/cryptpad/status/794574442030596096

**Pull request closed without merging**
