### PR TITLE
#169: First anchor test and restore of the CKEditor anchor function.

### PR DESCRIPTION
**Pull request by polx**

### CODE REVIEW

**Comment by ansuz** [comment]
It looks like our linter caught some undefined references

```
www/pad/inner.js: line 169, col 49, 'unescape' is not defined.
www/pad/inner.js: line 773, col 35, 'CKEDITOR' is not defined.
www/pad/inner.js: line 778, col 48, 'inner' is not defined.
```

Those may actually be undefined or out of scope, or you may just have to use `window.CKEDITOR`.

**Comment by ansuz** [comment]
I modified a few lines to make it pass our linter, and now the tests pass.

I'll need to look over the changes in more detail to make sure nothing breaks as a result. I'm most concerned about correctly reimporting content that was modified at export time.

**Comment by polx** [comment]
Thanks.
So... That looks like an extra (interesting) requirement.
Can you detail that in the issue maybe?
Is the fact that the data-attribute be (un)changed independently of the anchor a danger?

thanks

paul

**Comment by ansuz** [comment]
I don't know whether it's a danger, just that CKEditor is tricky sometimes. I did an export and import with some anchors, and if something is wrong, I can't tell.

**Comment by polx** [comment]
The reason I am asking, is that it seems like yet another step in test-automation.
paul

**Comment by polx** [comment]
Funnily, I saw recently that the read-only version also does not use the anchor (only the flag picture is there but no id or so; no scrolling that I could see).

**Pull request merged**
