### PR TITLE
Using express.static instead of custom handler

### PR DESCRIPTION
**Pull request by ochronus**
The original custom file handler code caused the server not sending the content-type header in some cases. This killed the site e.g. when using CloudFlare - safari tried to download the index.html instead of rendering it and chrome displayed the source code.

I might be missing something but I replaced that code with 2 simple express.static handlers - which handle content type (among other things) correctly

### CODE REVIEW

**Comment by ansuz** [comment]
At a glance, I'm not sure why the tests are failing.

I pulled your branch and tested locally, and everything seems good, so maybe it's just a CI issue.

**Comment by ochronus** [comment]
Yup it's a CI issue, the Chrome WebDriver is not installed there

**Comment by ansuz** [comment]
I hate to nitpick when you're improving things, but it looks like quite a few lines were changed for stylistic purposes alone.

Would you mind restricting it to the functional modifications?

**Comment by ochronus** [comment]
Please do "nitpick" :) I'm the new guy here and I'd like to accommodate to your coding style. Those changes were my editor being too smart automagically, sorry :) fix incoming

**Comment by ansuz** [comment]
Excellent, thanks!

**Pull request merged**
